@api_HostAddress = https://localhost:7052

GET {{api_HostAddress}}/weatherforecast/
Accept: application/json

###

### Test the API endpoint for submitting contact forms
POST {{api_HostAddress}}/api/contact
Content-Type: application/json

{
  "email": "test@example.com"
}

###
